cluster.name: map
node.name: "map-node-1"
http.cors.enabled: true
http.cors.allow-origin: /.*/
network.host: 0.0.0.0
# http.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
script.inline: true
# discovery.zen.ping.unicast.hosts: []
# discovery.zen.minimum_master_nodes: 1
node.master: true
node.data: true
#index.max_result_window : 500000
indices.query.bool.max_clause_count: 100240

path.repo: ["/usr/share/elasticsearch/data/backup"]